name: evolite
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - anyio=4.11.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - httpx-sse=0.4.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jiter=0.12.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - libcxx=21.1.6
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - msgpack-python=1.1.2
  - ncurses=6.5
  - openssl=3.6.0
  - orjson=3.11.4
  - packaging=25.0
  - pip=25.3
  - pycparser=2.22
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dotenv=1.2.1
  - python-xxhash=3.6.0
  - python_abi=3.11
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - setuptools=80.9.0
  - sniffio=1.3.1
  - tenacity=9.1.2
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - langchain==1.0.8
      - langchain-core==1.1.0
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.4.46
      - openai==2.8.1
      - ormsgpack==1.12.0
